#ifndef FPGA_PS_DRIVER_H
#define FPGA_PS_DRIVER_H

/* 如果要使用ps模式的config_done引脚，开启该条件宏 */
//#define FPGA_PS_CONF_DONE_USE

#define FPGA_PS_DRIVER_NAME "fpga_ps_driver"
#define FPGA_PS_NODE_NAME "fpga_ps_driver"

#define FPGA_PS_IOCTL_MAGIE 'F'
#define FPGA_PS_IOCTL_MAXNR 5
#define FPGA_PS_SELECT  _IOW(FPGA_PS_IOCTL_MAGIE, 0, char) 
#define FPGA_PS_PIN_INIT  _IOR(FPGA_PS_IOCTL_MAGIE, 1, char)
#define FPGA_PS_PIN_END  _IOR(FPGA_PS_IOCTL_MAGIE, 2, char)
#define FPGA_PS_CLEAN_PROG _IO(FPGA_PS_IOCTL_MAGIE, 3)
#define FPGA_PS_GPIO_INIT _IO(FPGA_PS_IOCTL_MAGIE, 4)

#define GN_FPGA_NUM								(2) /* fpga数目 */
typedef enum
{
	GN_FPGA_INDEX_MAIN = 0,
	GN_FPGA_INDEX_IP_ASI_OUTPUT,
	//add by leonli
	GN_FPGA_DVB_C_MODULE
}GN_FpgaIndex;

#define FPGA_MAIN_DCLK_PIN 	AT91_PIN_PC3
#define FPGA_MAIN_nCONFIG_PIN AT91_PIN_PC5
#define FPGA_MAIN_DATA_PIN AT91_PIN_PC6
#define FPGA_MAIN_nSTATUS_PIN AT91_PIN_PC2
#ifdef FPGA_PS_CONF_DONE_USE
#define FPGA_MAIN_CONF_DONE_PIN AT91_PIN_PC4
#endif

#define FPGA_IP_ASI_OUTPUT_DCLK_PIN 	AT91_PIN_PC11			
#define FPGA_IP_ASI_OUTPUT_nCONFIG_PIN AT91_PIN_PC13		
#define FPGA_IP_ASI_OUTPUT_DATA_PIN AT91_PIN_PC14					
#define FPGA_IP_ASI_OUTPUT_nSTATUS_PIN AT91_PIN_PC10	
#ifdef FPGA_PS_CONF_DONE_USE
#define FPGA_IP_ASI_OUTPUT_CONF_DONE_PIN AT91_PIN_PC12	
#endif

#define FPGA_PS_AUTHOR "Gospell"
#define FPGA_PS_DESCRIPTION FPGA_PS_DRIVER_NAME
#define FPGA_PS_LICENSE "GPL"

#define FPGA_PS_DATA_BUFFER_SIZE (128 * 1024 - 16) /* kmalloc最大分配128k-16字节，16个字节是被页描述符结构占用了 */

#endif /* FPGA_PS_DRIVER_H */
/* EOF */
